### ISSUE TITLE
Taxonomy: Dwkaselachus should be grouped in chondrichtyans

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/phenome-10k#3]
Nothing happens when I click Dwkaselachus on the taxonomy list, and it should be grouped in chondrichthyans, not as its own taxon.

**Comment by alycejenni** [comment]
I believe this was a GBIF grouping issue so it had to be added to the taxonomy table manually (but it does work as expected at the moment).
