### ISSUE TITLE
`Location` response headers are not HTTPS

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/phenome-10k#92]
Fixed on live but not in code.

Causes redirects to fail. Only thing that seems to have worked is adding to the nginx config:
> proxy_redirect http:// $scheme://;

Other methods (X-Forwarded-Proto, --forwarded-allow-ips, etc) couldn't get to work.

**Comment by alycejenni** [comment]
This is probably why everything broke when I redeployed the code 🙃 
Fixed now (both live and code).
